### ISSUE TITLE
Remove unused translation files

### ISSUE THREAD

**Issue by carly-cloud** [Adyen/adyen-web#1766]
Hello,

we are using the drop-in integration and I saw that all supported languages are add to the generated adyen.js (1MB)

Is there a way to just load languages we need to avoid a huge javascript file?

**Comment by marcel-wtfoxtrot** [comment]
Same here, even when providing custom Translations, all default translations are being imported.

**Comment by m1aw** [comment]
Hopefully this issue was solved by what was referred in #337. Going to close this thread.
Additionally using ES modules should fix this imports issues depending on bundler.

Feel free to reopen if additional information are needed.

**Comment by marcel-wtfoxtrot** [comment]
Hi @m1aw 

I can't confirm that using the modern Build is solving this performance issue.


I've create a simple Stackblitz (nuxt 3 / Vite) which is only using a sinple empy page and importing AdyenCheckout from `modern`.

In the terminal you'll find, that the build contains all languages.

https://stackblitz.com/edit/nuxt-starter-bi5unl?file=package.json,pages%2Findex.vue

Am i missing something?
Thank you.

![Bildschirmfoto 2022-10-21 um 18 12 11](https://user-images.githubusercontent.com/111567682/197241377-c54325c1-afc0-4d07-b58f-f00a2d069e1d.png)

**Comment by robinth91** [comment]
@m1aw I can confirm that using `es.modern` version of the library is not solving the issue. The translation files are still getting bundled.

**Comment by sponglord** [comment]
Closing this issue.
FYI - we are in the process of planning adyen-web v6. One of the man features of this will be a reduced bundle size (including a rethink on how we include the language files)
