### ISSUE TITLE
Types not resolved when using `moduleResolution: NodeNext` in tsconfig

### ISSUE THREAD

**Issue by sachinahya** [Adyen/adyen-web#2134]
**Describe the bug**

**To Reproduce**
1. Import the `@adyen/adyen-web` module in a TypeScript project that has `moduleResolution` set to `Node16`, `NodeNext` or `bundler`.
2. See error explaining the declaration file could not be found

```
Could not find a declaration file for module '@adyen/adyen-web'. '/Users/sachin/code/work/test/site/node_modules/@adyen/adyen-web/dist/es/index.js' implicitly has an 'any' type.
  There are types at '/Users/sachin/code/work/test/site/node_modules/@adyen/adyen-web/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@adyen/adyen-web' library may need to update its package.json or typings.ts(7016)
```

Reproduction - notice that changing `moduleResolution` to `node` causes the error to go away:
https://stackblitz.com/edit/typescript-yur3dk?file=index.ts

**Expected behavior**
The included types should be resolved by TypeScript and there are no type errors.

**Comment by ribeiroguilherme** [comment]
Hi @sachinahya ,

I'd like to understand a more which kind of web app you are working with.  What are the frameworks involved, and why do you need to use `NodeNext` or `Node16` as moduleResolution for your web app?

**Comment by sachinahya** [comment]
Hi, we need to use `Node16` as the `moduleResolution` because we're using `"type": "module"` in our package.json for ESM support. A number of third-party dependencies we are using are going ESM-only so we're updating our app to support them now that ESM support in Node has been stable for a while.

From what I understand, TypeScript aims to follow Node's resolution algorithm in this mode and only looks for types defined via the `exports` field. Since these are currently not specified, it fails to resolve the type declarations.

**Comment by FBisca** [comment]
I had the same problem.

The `"moduleResolution": "bundle"` also comes by default with NextJS 13 which might cause this problem to be more common as well.

**Comment by avez-fsd** [comment]
please help with this issue.

**Comment by ribeiroguilherme** [comment]
@sachinahya can you test again with the latest released version? We pushed a change that might fix this

**Comment by rehoutm** [comment]
I have a different issues, but I believe it is realted to the same root cause.

In our project, we are using ESM exclusively, with typescript resolvers set to `nodenext`. With this setup, importing adyen like this:

```
import AdyenCheckout from '@adyen/adyen-web'

// tsc will argue about this:

await await AdyenCheckout(...)
```

Instead, we have to make Typescript believe it's imported from it's `default` property like this:

```
import Adyen from '@adyen/adyen-web'

// ESM is great :/
export const AdyenCheckout = Adyen as unknown as typeof Adyen.default
```

and like that it works fine, but it's just an ugly hack.

I think that the issue is the fact that the adyen-web package itself is CJS, but it's type representation is ESM.

You can see a similar issue here https://github.com/microsoft/TypeScript/issues/53349

**Comment by ribeiroguilherme** [comment]
@rehoutm we are working on the next major version, and it will fully support ESM, so hopefully this compatibility issues will go away 🙏 

Regarding the issue related to this ticket - we released a fix in the previous version, therefore I am gonna close this ticket. Feel free to reach out if the issue persists.

**Comment by muhanad40** [comment]
Hi there, I can see that it's been a while since this was raised and unfortunately it's still an issue. Can someone give us an update on this? Thanks!

**Comment by ribeiroguilherme** [comment]
Hey @muhanad40 

There are two different issues in this thread - can you explain which one are you facing?
Besides that, can you share your current tech stack?

**Comment by muhanad40** [comment]
@ribeiroguilherme Thanks for getting back to me. We're trying to import a type like so and it's not working:
```typescript
import { PaymentMethodOptions } from '@adyen/adyen-web/dist/types/types'
```
The `moduleResolution` in `tsconfig.json` is set to `"Bundler"`

We need this type to ensure type safety when initialising `AdyenCheckout` for ApplyPay.

**Comment by ribeiroguilherme** [comment]
@muhanad40 and did you try the most recent version of adyen-web ? We did some improvements regarding the types, but I am not sure if that covers your issue.

What is your tech stack? Why is the moduleResolution set to 'Bundler'? 
I am asking this because we are working on the next major version (which also aims to fix all typescript issues) , so we can make sure to test it with your setup too.

**Comment by muhanad40** [comment]
@ribeiroguilherme Thanks for getting back to me. We've had to set `moduleResolution` to `Bundler` because we have a npm package that uses [Subpath Exports](https://nodejs.org/api/packages.html#subpath-exports). The only way for that to work is if the consuming project sets their `moduleResolution` to `Bundler`. This then stopped us from drilling into `/dist` of `adyen-web` to get types, which makes sense in my perspective. I think the author of the library should dictate what gets exposed and what doesn't because what if I grab a type that's not "officially" exposed and then it gets removed in later versions without notice.

**Comment by muhanad40** [comment]
@ribeiroguilherme We're using NextJS to build our application. We then have a npm package that provides various common utils across multiple applications. This is the package that we've updated to use **Subpath Exports** which then broke our type imports from `adyen-web`. What else would you like to know about the stack?
