### ISSUE TITLE
v5.41.0: Cannot read properties of undefined (reading 'getImage')

### ISSUE THREAD

**Issue by pguilbert** [Adyen/adyen-web#2135]
**Describe the bug**

We are using the [Adyen custom card integration](https://docs.adyen.com/payment-methods/cards/custom-card-integration).

After updating to the new 5.41.0 version of the package we no longer received `onChange` event from the secured fields. 

This makes the form unusable, we had to revert to the previous version.

**To Reproduce**

Our integration is similar to the [documentation](https://docs.adyen.com/payment-methods/cards/custom-card-integration).

```
  this.checkoutInstance = await AdyenCheckout({
    locale: this.locale,
    clientKey: this.adyenPublicKey,
    environment: this.adyenEnvironment,
  })

const component = this.checkoutInstance.create('securedfields', {
      type: 'card',
      styles: ADYEN_COMPONENT_STYLES,

      onConfigSuccess: () => {
        resolve()
      },

      onError: (payload) => {
        reject(Object.assign(new Error(payload?.error), { payload }))
      },

      onBrand: (payload) => {
        this.brandPayload = cloneDeep(payload)
      },
      onChange: (payload) => {
        console.log('onChange', payload)
        this.changePayload = cloneDeep(payload)
      },
      onFocus: (payload) => {
        this.focusPayload = cloneDeep(payload)
      },
    })

    component.mount(container)
  })
```

The `console.log('onChange', payload)` is called once when the form is initialized, but never after. I can see the following console log as soon as I type in the card number field:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getImage')
    at Qr (index.js?57f2:1:1)
    at $s.eval (index.js?57f2:1:1)
    at eval (preact.module.js?da65:1:1)
    at Array.some (<anonymous>)
    at eval (preact.module.js?da65:1:1)
    at Array.some (<anonymous>)
    at z (preact.module.js?da65:1:1)
    at eval (preact.module.js?da65:1:1)
    at Array.some (<anonymous>)
    at g (preact.module.js?da65:1:1)
```

**Screenshots**
<img width="607" alt="image" src="https://user-images.githubusercontent.com/3878835/236237315-81937eb6-b63c-4691-a847-5b5ad491f5aa.png">.

**Desktop:**
 - OS: MAC
 - Browser: chrome
 - Version : 111

Thank you in advance!

**Comment by m1aw** [comment]
Hell @pguilbert. This issue has been fixed on version `v5.42.x` feel free to upgrade and thank you for reporting it to us. We will close the ticket for now but feels free to update us if any other problems arise.

**Comment by meinenieuwland** [comment]
This is still a bug in `5.42.1`

**Comment by pguilbert** [comment]
> Hell @pguilbert. This issue has been fixed on version `v5.42.x` feel free to upgrade and thank you for reporting it to us. We will close the ticket for now but feels free to update us if any other problems arise.

Hello @m1aw , 
As mentioned by @meinenieuwland the issue is still present in v5.42.1. With the same console log `Cannot read properties of undefined (reading 'getImage')`

**Comment by ribeiroguilherme** [comment]
Hi @pguilbert, @meinenieuwland  - we released version 5.43.0 which contains the fix for the problem. Can you please take a look and let us know if the problem is solved? Thanks

**Comment by meinenieuwland** [comment]
> Hi @pguilbert, @meinenieuwland - we released version 5.43.0 which contains the fix for the problem. Can you please take a look and let us know if the problem is solved? Thanks

Hi @ribeiroguilherme, I just tested it on our stack and I can confirm that this bug is fixed as far that I can see. Thanks for fixing it 👍

**Comment by ribeiroguilherme** [comment]
Glad it worked. I am closing this issue for now then. Thanks for reaching out. Cheers!
